### PR TITLE
Allow setting video scale

### PR DESCRIPTION
**Pull request by pwespi**
Currently the output resolution of the video is hard-coded to 1200 x height.

This PR allows setting the scale flag that is passed to ffmpeg to customize the output resolution. The default is the same as the currently hard-coded value.

### CODE REVIEW

**Comment by pwespi** [comment]
@christian-bromann any chance you could take a look at this? Thanks!

**Comment by christian-bromann** [comment]
@pwespi can we remove the files checked into the `dist` directory? I don't think they are suppose to be in the repo, right?

**Comment by pwespi** [comment]
> @pwespi can we remove the files checked into the `dist` directory? I don't think they are suppose to be in the repo, right?

I agree. I just updated them because they were there before.

Added another commit to remove the dist folder.

**Review by christian-bromann — APPROVED** [review]
Thank you 👍

**Comment by pwespi** [comment]
@christian-bromann  Thanks for merging. And thanks for your great work on WebdriverIO in general! 🚀

**Pull request merged**
