### PR TITLE
Add support for multiremote

### PR DESCRIPTION
**Pull request by kevinmcdonnell**
Webdriverio has a feature called multiremote https://webdriver.io/docs/multiremote.html
It allows to drive multiple browsers at the same time

This pr adds support for multiremote.

There doesn't appear to be a way to easily fetch browser instances, so this pr checks for `isMultiremote` and gets the names of those browser. It then calls saveScreenshot assume a global var exists with that same name

I can tidy up this further, particularly the objects created in `getBrowsers`. It also needs some further testing.

I wanted to get some feedback before proceeding further?

### CODE REVIEW

**Comment by presidenten** [comment]
Thanks! This looks really interesting. 
I am however on vacation for a few weeks now. Do you have an urgent need for this to be fixed during the summer, or can it wait until August?

**Comment by kevinmcdonnell** [comment]
We can wait, I may copy this code into our project in the interim

**Comment by presidenten** [comment]
Im back from the vacation and will try to make time to have a closer look at this

**Comment by christian-bromann** [comment]
I will go ahead and close this given there hasn't been much activity for 3 years. The code base hasn't changed much but it is still easier to start this effort from scratch rather than trying to rebase this one. Any contributions would be welcome, thanks!

**Pull request closed without merging**
