### PR TITLE
support nice-html-reporter by sending video-capture event at appropri…

### PR DESCRIPTION
**Pull request by rpii**
This pull request adds code to fire an event that nice-html-reporter receives and allows it to capture each video that is created by the wdio-video-reporter.  low risk change.  
Works with version 7.9.1 of nice-html-reporter  (git@github.com:rpii/wdio-html-reporter.git)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@rpii thanks, happy to merge! Can you make an addition an mention the compatibility in the readme?

**Comment by rpii** [comment]
Yes I can

**Comment by rpii** [comment]
Ok I updated the readme in the fork.

**Review by christian-bromann — APPROVED** [review]
Thank you 👍

**Pull request merged**
